url_encode js search data content
When building the js search data, we are creating a json data structure with each
page content as one long string in that data structure. If there are unescaped
special characters (like any of these
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Escape_notation)
then we could end up with a javascript syntax error, e.g. 'Uncaught
SyntaxError: Invalid Unicode escape sequence' instead of working search
functionality. We have some unescaped special characters in some code blocks,
like some windows examples with '\Talon\user' where the unescpaed '\u' is
interpreted as a unicode sequence that expects some digits after it.

This change adds url_encode to the template when we generate the search data,
which will escape any special characters and avoid getting javascript syntax
errors.